services:
  - type: web
    name: poker-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
